### ISSUE TITLE
Remove Cards

### ISSUE THREAD

**Issue by janzeng** [cs361fall2017/team2#1]
Card: "As a player, I want to be able to remove matching suit cards in order to progress in the game."

Conversation: Which cards can be removed? If there are 2 or more cards of the same suit top of the columns, the lower card may be removed. When can you remove cards? You can remove cards at any time as long as there is a legal move available.

Confirmation: Developer will try both legal and illegal removal of cards to see if the rules are applied and the removal actually works where valid.

Timeline: This issue must be completed by 10/13.

**Comment by janzeng** [comment]
This has been merged and removing cards is now working.

**Comment by AntonSynytsiaOSU** [comment]
Verified

**Comment by iamalotaibi** [comment]
There is a problem when removing a card and there is an empty column, the game won't remove that card.
You should add this to your code:
public void remove(int columnNumber) {
// remove the top card from the indicated column
if (columnNumber > 3 || columnNumber < 0 || !(columnHasCards(columnNumber)))
return;
...}

**Comment by janzeng** [comment]
Thanks for catching that! I edited the function, also adding error statements when the user attempts an illegal move.
