### ISSUE TITLE
Deal Cards

### ISSUE THREAD

**Issue by AntonSynytsiaOSU** [cs361fall2017/team2#2]
The "Deal" button doesn't work. 
* When a new game is created, four cards should be dealt automatically.
* Clicking the “Deal” button should take the top, four cards from the deck and place one in each column, at their desired rows.
* When all 52 cards are dealt, the button should do nothing.
* Every time a new game is created, cards should be shuffled into a unique and random order.

Timeline: This issue must be completed by 10/13.

**Comment by iamalotaibi** [comment]
I have tested "Deal Cards" issue and it worked as it needed to be.
